### ISSUE TITLE
No active screen error

### ISSUE THREAD

**Issue by devsnek** [lyonlai/blessed-vue#5]
```js
const Vue = require('blessed-vue');

const el = Vue.dom.createElement();
Vue.dom.append(el);

new Vue({
  name: 'app',
  components: {},
  template: '<box></box>',
}).$mount(el);
```

this code produces the error below
```
./node_modules/blessed/lib/widgets/node.js:57
      throw new Error('No active screen.');
      ^

Error: No active screen.
    at Box.Node (./node_modules/blessed/lib/widgets/node.js:57:13)
    at Box.Element (./node_modules/blessed/lib/widgets/element.js:49:8)
    at new Box (./node_modules/blessed/lib/widgets/box.js:23:11)
    at Function.Box (./node_modules/blessed/lib/widgets/box.js:20:12)
    at Object.createElement$1 [as createElement] (./node_modules/blessed-vue/dist/build.js:4680:25)
    at createElm (./node_modules/blessed-vue/dist/build.js:4915:19)
    at Vue$3.patch [as __patch__] (./node_modules/blessed-vue/dist/build.js:5382:9)
    at Vue$3.Vue._update (./node_modules/blessed-vue/dist/build.js:2289:19)
    at Vue$3.updateComponent (./node_modules/blessed-vue/dist/build.js:2412:10)
    at Watcher.get (./node_modules/blessed-vue/dist/build.js:2751:25)
```

**Comment by lyonlai** [comment]
right, hmm. you need to wrap the box component with a screen component. checkout https://github.com/lyonlai/blessed-vue/blob/master/examples/call-log/log.vue

**Comment by devsnek** [comment]
@lyonlai I actually first got this error when running the dashboard example, then mistakenly created the above code when trying to provide a reproducable code sample. I still get this error running the dashboard example which does appear to have a screen on it.

**Comment by devsnek** [comment]
@lyonlai this issue still occurs with the dashboard example, i haven't tested others. blessed-vue@1.2.0 from npm was used

**Comment by lyonlai** [comment]
@devsnek  hmm. are you able to run the example in the repo?

**Comment by devsnek** [comment]
That's the example I'm trying

**Comment by devsnek** [comment]
@lyonlai any word on this?

**Comment by xdissent** [comment]
The issue is likely that you're requiring a copy of blessed to create your screen, but blessed-vue is using its own copy of blessed. Unfortunately the blessed module stores global state, so if you're not using exactly one blessed module, it won't work. Check your `node_modules` for two copies of blessed and try to dedupe it to one shared copy.
